spring:
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/ORCL
    username: HR
    password: 123456
    driver-class-name: oracle.jdbc.driver.OracleDriver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
      dialect: org.hibernate.dialect.Oracle11gDialect

